# Numpy

- N-dimensional arrays: 
    - NumPy provides the ndarray (n-dimensional array) object for efficient storage and manipulation of large arrays of homogeneous data (e.g., numbers).
- Mathematical operations: 
    - NumPy provides many mathematical functions such as 
        - trigonometric, 
        - logarithmic, and 
        - linear algebra functions that can operate on entire arrays.
- Broadcasting: 
    - NumPy allows you to perform operations on arrays of different shapes by automatically broadcasting smaller arrays to match the shape of larger arrays.
- Interoperability: 
    - NumPy is designed to work seamlessly with other libraries, such as Pandas, and is often used as the underlying data structure for other scientific libraries.
    
Pandas and NumPy are often used together in data analysis tasks

NumPy provides the low-level array operations.

In [3]:
import numpy as np

# N-dimensional arrays
# Create a 1-dimensional array
array1d = np.array([1, 2, 3, 4, 5])
print("1-dimensional array:")
print(array1d)

# Create a 2-dimensional array
array2d = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2-dimensional array:")
print(array2d)

# Mathematical operations
# Trigonometric functions
sin_values = np.sin(array1d)
print("\nSin values:")
print(sin_values)

# Logarithmic functions
log_values = np.log(array1d)
print("\nLog values:")
print(log_values)

# Linear algebra functions
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
matrix_product = np.dot(matrix1, matrix2)
print("\nMatrix product:")
print(matrix_product)

# Broadcasting
array3 = np.array([10, 20, 30, 10, 20])
array_broadcasted = array1d + array3
print("\nBroadcasted array:")
print(array_broadcasted)

# Interoperability
import pandas as pd

data = {'col1': [1, 2, 3, 4, 5],
        'col2': ['A', 'B', 'C', 'D', 'E']}
df = pd.DataFrame(data)

numpy_array = df['col1'].to_numpy()
print("\nNumPy array from DataFrame:")
print(numpy_array)

1-dimensional array:
[1 2 3 4 5]

2-dimensional array:
[[1 2 3]
 [4 5 6]]

Sin values:
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]

Log values:
[0.         0.69314718 1.09861229 1.38629436 1.60943791]

Matrix product:
[[19 22]
 [43 50]]

Broadcasted array:
[11 22 33 14 25]

NumPy array from DataFrame:
[1 2 3 4 5]


### Working with Numpy
- Numpy is a python library for scientific computing
    - To Work with multidimensional array objects and 
    - used to handle large amount of data. 
- An array which is a grid of values and is indexed by a tuple of nonnegative integers is main data structure of the Numpy library.
- ndarray is acronym of N-Dimensional Array.
- We will cover:
    - Flattening the arrays, 
    - Concatenation arrays and 
    - Broadcasting arrays
    
##### In Numpy, you must know:

In [4]:
import numpy as np

# Create NumPy arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([[1, 2, 3], [4, 5, 6]])
array3 = np.array([1.1, 2.2, 3.3, 4.4, 5.5])

print("NumPy arrays:")
print("Array 1:", array1)
print("Array 2:")
print(array2)
print("Array 3:", array3)

NumPy arrays:
Array 1: [1 2 3 4 5]
Array 2:
[[1 2 3]
 [4 5 6]]
Array 3: [1.1 2.2 3.3 4.4 5.5]


In [5]:
# Zeros arrays
zeros_array = np.zeros((2, 3))
print("\nZeros array:")
print(zeros_array)


Zeros array:
[[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
# Ones arrays
ones_array = np.ones((3, 2))
print("\nOnes array:")
print(ones_array)


Ones array:
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [7]:
# Full arrays
full_array = np.full((2, 2), 5)
print("\nFull array:")
print(full_array)


Full array:
[[5 5]
 [5 5]]


In [8]:
# Identity Matrix
identity_matrix = np.eye(3)
print("\nIdentity matrix:")
print(identity_matrix)


Identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
# Reshape array
reshaped_array = np.reshape(array1, (5, 1))
print("\nReshaped array:")
print(reshaped_array)


Reshaped array:
[[1]
 [2]
 [3]
 [4]
 [5]]


In [10]:
# Flatten array
flattened_array = array2.flatten()
print("\nFlattened array:")
print(flattened_array)


Flattened array:
[1 2 3 4 5 6]


In [11]:
# Concatenation
concatenated_array = np.concatenate((array1, array3))
print("\nConcatenated array:")
print(concatenated_array)


Concatenated array:
[1.  2.  3.  4.  5.  1.1 2.2 3.3 4.4 5.5]


In [12]:
# Broadcasting
broadcasted_array = array1 + 10
print("\nBroadcasted array:")
print(broadcasted_array)


Broadcasted array:
[11 12 13 14 15]


In [13]:
# Scalar product
scalar_product = np.dot(array1, array3)
print("\nScalar product:")
print(scalar_product)


Scalar product:
60.5


### Important functions in NumPy

- np.array(): 
    - This function is used to create a new NumPy array from a Python list or another array-like object.

In [14]:
import numpy as np

# np.array()
arr1 = np.array([1, 2, 3, 4, 5])
print("Array 1:", arr1)

arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("Array 2:")
print(arr2)

Array 1: [1 2 3 4 5]
Array 2:
[[1 2 3]
 [4 5 6]]


- np.zeros() and np.ones(): 
    - These functions are used to create new arrays filled with zeros or ones, respectively.

In [ ]:
# np.zeros() and np.ones()
zeros_arr = np.zeros((3, 4))
print("Zeros array:")
print(zeros_arr)

ones_arr = np.ones((2, 2))
print("Ones array:")
print(ones_arr)

- np.shape and np.ndim: 
    - These functions are used to get the shape (number of rows and columns) and dimension (number of axes) of an array, respectively.

In [15]:
# np.shape and np.ndim
print("Shape of arr2:", np.shape(arr2))
print("Dimension of arr2:", np.ndim(arr2))

Shape of arr2: (2, 3)
Dimension of arr2: 2


- np.arange(): 
    - This function is used to create a new array with a range of evenly spaced values.

In [16]:
# np.arange()
arr3 = np.arange(1, 10, 2)
print("Array 3 (arange):")
print(arr3)

Array 3 (arange):
[1 3 5 7 9]


- np.linspace(): 
    - This function is used to create a new array with a specified number of evenly spaced values between two endpoints.

In [17]:
# np.linspace()
arr4 = np.linspace(0, 1, 5)
print("Array 4 (linspace):")
print(arr4)

Array 4 (linspace):
[0.   0.25 0.5  0.75 1.  ]


- np.random.rand() and np.random.randn(): 
    - These functions are used to create new arrays with random values sampled from a uniform or normal distribution, respectively.

In [19]:
# np.random.rand() and np.random.randn()
rand_arr = np.random.rand(2, 3)
print("Random array:")
print(rand_arr)

randn_arr = np.random.randn(2, 3)
print("Random normal array:")
print(randn_arr)

Random array:
[[0.5140203  0.50309771 0.58716292]
 [0.71402906 0.45761324 0.63826086]]
Random normal array:
[[-0.38413664  0.46757413  1.00242686]
 [ 1.82265249 -1.70083974  0.87595736]]


- np.min() , np.max(), np.mean(), np.sum(): 
    - These functions are used to find the minimum, maximum, mean and sum of array elements

In [20]:
# np.min(), np.max(), np.mean(), np.sum()
print("Minimum value in arr1:", np.min(arr1))
print("Maximum value in arr1:", np.max(arr1))
print("Mean of arr1:", np.mean(arr1))
print("Sum of arr1:", np.sum(arr1))

Minimum value in arr1: 1
Maximum value in arr1: 5
Mean of arr1: 3.0
Sum of arr1: 15


- np.dot() and np.matmul(): 
    - These functions are used to perform matrix multiplication on two arrays.

In [21]:
# np.dot() and np.matmul()
arr5 = np.array([[1, 2], [3, 4]])
arr6 = np.array([[5, 6], [7, 8]])
dot_product = np.dot(arr5, arr6)
matmul_product = np.matmul(arr5, arr6)
print("Dot product:")
print(dot_product)
print("Matrix multiplication:")
print(matmul_product)

Dot product:
[[19 22]
 [43 50]]
Matrix multiplication:
[[19 22]
 [43 50]]


- np.transpose() and np.reshape(): 
    - These functions are used to change the shape of an array, transpose flips the array along its diagonal and reshape changes the shape of an array without changing its data

In [22]:
# np.transpose() and np.reshape()
transposed_arr2 = np.transpose(arr2)
reshaped_arr1 = np.reshape(arr1, (5, 1))
print("Transposed arr2:")
print(transposed_arr2)
print("Reshaped arr1:")
print(reshaped_arr1)

Transposed arr2:
[[1 4]
 [2 5]
 [3 6]]
Reshaped arr1:
[[1]
 [2]
 [3]
 [4]
 [5]]


- np.save() and np.load(): 
    - These functions are used to save an array to a binary file and load it again later.

In [23]:
# np.save() and np.load()
np.save("saved_array", arr1)
loaded_arr = np.load("saved_array.npy")
print("Loaded array:")
print(loaded_arr)

Loaded array:
[1 2 3 4 5]
